import os


TEST_ENV = {
    "APPLICATION_TITLE": "FastAPI DDD Backend Skeleton",
    "APPLICATION_SUMMARY": "Test summary",
    "APPLICATION_DESCRIPTION": "Test description",
    "APPLICATION_VERSION": "0.1.0",
    "APPLICATION_CONTACT_NAME": "Test Team",
    "APPLICATION_CONTACT_URL": "http://localhost:8000/docs",
    "APPLICATION_CONTACT_EMAIL": "team@example.com",
    "APPLICATION_CONTACT_PHONE": "+1 000 000 0000",
    "APPLICATION_ENVIRONMENT": "dev",
    "APPLICATION_PORT": "8000",
    "APPLICATION_CONNECT_TIMEOUT_SECONDS": "30",
    "APPLICATION_URL": "http://localhost:8000",
    "APPLICATION_TABLE_PREFIX": "fastapi_ddd",
    "AUTH_BEARER_TOKEN_SCHEME_NAME": "BearerAuth",
    "AUTH_BEARER_TOKEN_SCHEME_DESCRIPTION": "Bearer token authentication using JWT.",
    "AUTH_API_KEY_SCHEME_NAME": "ApiKeyAuth",
    "AUTH_API_KEY_SCHEME_DESCRIPTION": "API key authentication using the X-API-Key header.",
    "AUTH_API_KEY_HEADER": "X-API-Key",
    "AUTH_API_KEY_HEADER_DESCRIPTION": "API key to access the application.",
    "COOKIES_MAX_AGE_SECONDS": "3600",
    "COOKIES_TOKEN_TYPE_KEY": "token_type",
    "COOKIES_ACCESS_TOKEN_KEY": "access_token",
    "COOKIES_ACCESS_TOKEN_PATH": "/",
    "COOKIES_REFRESH_TOKEN_KEY": "refresh_token",
    "COOKIES_REFRESH_TOKEN_PATH": "/api/v1/authentication/refresh",
    "COOKIES_DEVICE_KEY": "device_id",
    "COOKIES_DOMAIN": "localhost",
    "JWT_ISSUER": "fastapi-ddd",
    "JWT_AUDIENCE": "fastapi-ddd-clients",
    "JWT_SIGNING_KEY_PASSWORD": "change-me-signing-password",
    "JWT_ENCRYPTION_KEY_PASSWORD": "change-me-encryption-password",
    "JWT_SIGNING_PRIVATE_KEY_PATH": "secrets/keys/signing-private.pem",
    "JWT_SIGNING_PUBLIC_KEY_PATH": "secrets/keys/signing-public.pem",
    "JWT_ENCRYPTION_PRIVATE_KEY_PATH": "secrets/keys/encryption-private.pem",
    "JWT_ENCRYPTION_PUBLIC_KEY_PATH": "secrets/keys/encryption-public.pem",
    "JWT_ACCESS_TOKEN_EXPIRE_MINUTES": "15",
    "JWT_REFRESH_TOKEN_EXPIRE_DAYS": "7",
    "JWT_HASH_FINGERPRINT": "change-me-fingerprint",
    "LOGS_NAME": "fastapi-ddd",
    "LOGS_PATH": "logs",
    "LOGS_LEVEL": "INFO",
    "LOGS_REQUEST_ID_LENGTH": "8",
    "POSTGRESQL_DATABASE": "fastapi_ddd",
    "POSTGRESQL_USERNAME": "fastapi_ddd",
    "POSTGRESQL_PASSWORD": "fastapi_ddd",
    "POSTGRESQL_HOST": "localhost",
    "POSTGRESQL_PORT": "5432",
    "SECURITY_ALLOW_ORIGINS": '["http://localhost:3000","http://localhost:8000"]',
    "SECURITY_ALLOW_HEADERS": '["Authorization","Content-Type","X-API-Key"]',
    "SECURITY_ALLOW_METHODS": '["GET","POST","PATCH","DELETE","OPTIONS"]',
    "SECURITY_EMAIL_ALLOWED_DOMAINS": '["example.com"]',
    "SECURITY_ADMIN_EMAIL": "admin@example.com",
    "SECURITY_ADMIN_PASSWORD": "change-me-admin-password",
}


for key, value in TEST_ENV.items():
    os.environ.setdefault(key, value)
